// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
class PigeonStats {
  init(
    weight: Int64,
    name: String
  ) {
    self.weight = weight
    self.name = name
  }
  var weight: Int64
  var name: String

  static func fromList(_ list: [Any?]) -> PigeonStats? {
    let weight = list[0] is Int64 ? list[0] as! Int64 : Int64(list[0] as! Int32)
    let name = list[1] as! String

    return PigeonStats(
      weight: weight,
      name: name
    )
  }
  func toList() -> [Any?] {
    return [
      weight,
      name,
    ]
  }
}

private class DemoApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return PigeonStats.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DemoApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonStats {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DemoApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DemoApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DemoApiCodecWriter(data: data)
  }
}

class DemoApiCodec: FlutterStandardMessageCodec {
  static let shared = DemoApiCodec(readerWriter: DemoApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DemoApi {
  func pokePigeon() throws
  func makePigeonSpeak(text: String) throws -> String
  func getPigeonStats(completion: @escaping (Result<PigeonStats, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DemoApiSetup {
  /// The codec used by DemoApi.
  static var codec: FlutterStandardMessageCodec { DemoApiCodec.shared }
  /// Sets up an instance of `DemoApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DemoApi?) {
    let pokePigeonChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_demo.DemoApi.pokePigeon", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pokePigeonChannel.setMessageHandler { _, reply in
        do {
          try api.pokePigeon()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pokePigeonChannel.setMessageHandler(nil)
    }
    let makePigeonSpeakChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_demo.DemoApi.makePigeonSpeak", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      makePigeonSpeakChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        do {
          let result = try api.makePigeonSpeak(text: textArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      makePigeonSpeakChannel.setMessageHandler(nil)
    }
    let getPigeonStatsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_demo.DemoApi.getPigeonStats", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPigeonStatsChannel.setMessageHandler { _, reply in
        api.getPigeonStats { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPigeonStatsChannel.setMessageHandler(nil)
    }
  }
}
