// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PigeonStats;

@interface PigeonStats : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithWeight:(NSInteger )weight
    name:(NSString *)name;
@property(nonatomic, assign) NSInteger  weight;
@property(nonatomic, copy) NSString * name;
@end

/// The codec used by DemoApi.
NSObject<FlutterMessageCodec> *DemoApiGetCodec(void);

@protocol DemoApi
- (void)pokePigeonWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)makePigeonSpeakText:(NSString *)text error:(FlutterError *_Nullable *_Nonnull)error;
- (void)getPigeonStatsWithCompletion:(void (^)(PigeonStats *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpDemoApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DemoApi> *_Nullable api);

NS_ASSUME_NONNULL_END
